steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/api', './api']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/api']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'api', '--image', 'gcr.io/$PROJECT_ID/api', '--region', 'us-west1', '--allow-unauthenticated']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/web', './website/production']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/web']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'web', '--image', 'gcr.io/$PROJECT_ID/web', '--region', 'us-west1', '--allow-unauthenticated']
logsBucket: 'gs://gradeview-deploy-bucket'
