image: docker:23.0.0
services:
  - docker:23.0.0-dind

stages:
  - Build

build_job:
  stage: Build
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - apk update && apk add jq
  - export API_VERSION=$(jq -r .version ./api/package.json)
  - export WEB_VERSION=$(jq -r .version ./website/production/package.json)
  - cd website
  - apk add --update nodejs npm
  - npm install
  - npm run build
  - cd ..
  - docker-compose build
  - docker-compose push
  - docker logout