image: docker:23.0.0
services:
  - docker:23.0.0-dind
stages:
  - Build

build_job:
  stage: Build
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker-compose build
  - docker-compose push
  - docker logout