version: '3.8'
services:
  web:
    container_name: gradeview-web
    image: $CI_REGISTRY_IMAGE/web:$WEB_VERSION
    build: ./website/production
    ports:
      - 3000:3000
    command: npm start
  api:
    container_name: gradeview-api
    image: $CI_REGISTRY_IMAGE/server:$API_VERSION
    build: ./api
    volumes:
      - ./api:/api
    ports:
      - 8000:8000
    command: npm run server
