version: '3.8'
services:
  web:
    container_name: gradeview-web
    image: gradeview-website
    build: ./website
    volumes:
      - ./website:/website
    ports:
      - 3000:3000
    command: npm run react
  server:
    container_name: gradeview-server
    image: gradeview-server
    build: ./server
    volumes:
      - ./server:/server
    ports:
      - 8000:8000
    command: npm run server
