version: '3.8'
services:
  web:
    container_name: gradeview-web
    image: ${CI_REGISTRY_IMAGE:-gradeview}/web:${WEB_VERSION:-development}
    volumes:
      - ${SOCKETS_DIR:-/dev/null}:/run/sockets
    build: ./website/server
    ports:
      - 3000:3000
    command: npm start
  api:
    container_name: gradeview-api
    image: ${CI_REGISTRY_IMAGE:-gradeview}/server:${API_VERSION:-development}
    build: ./api
    volumes:
      - ./api:/api
    ports:
      - 8000:8000
    command: npm start
  dtgui:
    build: ./dtgui
    restart: always
    expose:
      - 8080
    ports:
      - 8080:8080
